### ISSUE TITLE
black screen when running magic mirror

### ISSUE THREAD

**Issue by raymondpadgett** [AdamMoses-GitHub/MMM-TweetsByTimelineOrList#8]
black screen when running magic mirror after adding the module and editing the config file

**Comment by SkySails** [comment]
I have the same issue. Followed the instructions, still get a black screen when starting MM with the module configured.

**Comment by AdamMoses-GitHub** [comment]
Let me have a look.

**Comment by malu58** [comment]
I have also a black screen on this position. After restart pm2 I can see for 3 sec: Awaiting Update...

**Comment by minhduccao** [comment]
I'm also running into the same issue as malu58 where MagicMirror loads fine but it only displays: "Awaiting Update..." at the bottom left of the screen upon load. Even when my timeline updates on Twitter, it doesn't seem to update on the screen even after 8 minutes (past the 5 minute refresh period).

I have followed the instructions specified by installing the twitter and bad-words packages, used my access tokens and keys, and used my Twitter handle for 'screenName'. All other settings have been left unchanged. I am currently using node.js version 10.15.2 and npm version 5.8.0. It is currently displaying a warning in the console that npm does not support the Node.js version upon load.

If needed, I can attach screenshots of the npm/node warning and the console logs.

**Comment by kk69bs** [comment]
On  latest Rasbian version the new MagicMirror installation worked fine until I added any external module. The screen shows only a black screen. Here is the terminal response:
```
pi@KPI5:~/MagicMirror $ DISPLAY=:0 npm start

> magicmirror@2.9.0 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.9.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'node_helper'
Loading module helpers ...
No helper found for module: alert.
App threw an error during load
Error: Cannot find module 'node_helper'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/default/updatenotification/node_helper.js:6:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/default/updatenotification/node_helper.js:100:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
Whoops! There was an uncaught exception...
{ Error: Cannot find module 'node_helper'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/default/updatenotification/node_helper.js:6:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/default/updatenotification/node_helper.js:100:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32) code: 'MODULE_NOT_FOUND' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.
^C
```
Thanks for any helping hint!

**Comment by snowthrills** [comment]
I had a similar error immediately after installing this module. 
I found this error was resolved by running git status and finding out **modules/node_modules/node_helper/index.js** was deleted

`git status` 
revealed the following
> deleted:          modules/node_modules/node_helper/index.js

![image](https://user-images.githubusercontent.com/24442856/68610914-e3ab3b00-0486-11ea-81fd-f70fcb7097ae.png)


I am completely back in business after running 
`git checkout -- modules/node_modules/node_helper/index.js`

**Comment by snowthrills** [comment]
@AdamMoses-GitHub I don't know if this helps you but I narrowed the "modules/node_modules/node_helper/index.js" deletion down to running both 'npm install twitter' and 'npm install bad-words from within the module directly as per the instructions in the readme. After each run i noticed the index.js file was deleted.

>
